server:
  port: 8081
  forward-headers-strategy: framework

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: admin-m2

spring:
  application:
    name: api-password-service
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/passwords?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: vilaswifi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.100:8080/realms/m2

  liquibase:
    enabled: false
logging:
  level:
    org:
      springframework:
        security=DEBUG:
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
    enabled: true
    disable-swagger-default-url: true
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  show-actuator: false
management:
  endpoints:
    web:
      exposure:
        include: health
