server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-password-service
  datasource:
    url: jdbc:mysql://localhost/seguridad_m1
    username: root
    password: P4ssw0rd!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
    enabled: true
    disable-swagger-default-url: true
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  show-actuator: true
