name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SKIP_ACCEPTANCE_TEST: true
  JAVA_IMAGE: 'eclipse-temurin:21-jdk-alpine'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

  # Etapa de Test
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: mvn test

      # Saltar pruebas de aceptación si está configurado
      - name: Skip acceptance tests (if enabled)
        if: ${{ env.SKIP_ACCEPTANCE_TEST == 'true' }}
        run: echo "Skipping acceptance tests"

  # Etapa de Package
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package application
        run: mvn package

  # Etapa de Publish
