name: production-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SKIP_ACCEPTANCE_TEST: true
  JAVA_IMAGE: 'eclipse-temurin:21-jdk-alpine'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            **/gradle-wrapper.properties
            **/*.gradle
      - run: ./gradlew build --no-daemon

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            **/gradle-wrapper.properties
            **/*.gradle

      - name: Run unit tests
        run: ./gradlew test --no-daemon

      - name: Skip acceptance tests (if enabled)
        if: ${{ env.SKIP_ACCEPTANCE_TEST == 'true' }}
        run: echo "Skipping acceptance tests"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from build.gradle
        id: extract_version
        run: |
          VERSION=$(grep -oP 'version\\s*=\\s*\"\\K[0-9.]+(?=\")' build.gradle)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mferrerovilas/api-password:${{ env.version }} .
          docker tag mferrerovilas/api-password:${{ env.version }} mferrerovilas/api-password:latest
          docker push mferrerovilas/api-password:${{ env.version }}
          docker push mferrerovilas/api-password:latest
