name: production-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SKIP_ACCEPTANCE_TEST: true
  JAVA_IMAGE: 'eclipse-temurin:21-jdk-alpine'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
         path: ~/.gradle/caches
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
         restore-keys: |
           ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean build


  # Etapa de Test
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: ./gradlew test

      - name: Skip acceptance tests (if enabled)
        if: ${{ env.SKIP_ACCEPTANCE_TEST == 'true' }}
        run: echo "Skipping acceptance tests"

  # Etapa de Package
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package application
        run: ./gradlew assemble

  # Etapa de Publish
