name: general-pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      PORTAINER_HOST: "${{ secrets.PORTAINER_HOST }}"
      PORTAINER_USERNAME: "${{ secrets.PORTAINER_USERNAME }}"
      PORTAINER_PASSWORD: "${{ secrets.PORTAINER_PASSWORD }}"

